import {
  Aperture,
  Crop,
  FileImage,
  ImageDown,
  Images,
  Maximize2,
  PenLine,
  RefreshCw,
  ScanFace,
} from "lucide-react";
import type { ToolConfig } from "@/types/tool";

export const tools: ToolConfig[] = [
  {
    name: "Compress Image",
    slug: "compress-image",
    description: "Shrink JPG, PNG, and WebP files without a watermark.",
    longDescription: "Reduce image file size in your browser while keeping the visual quality you choose.",
    category: "Optimization",
    status: "active",
    icon: ImageDown,
    accent: "mint",
    related: ["resize-image", "convert-image", "resize-image-to-kb"],
  },
  {
    name: "Resize Image",
    slug: "resize-image",
    description: "Set exact dimensions or scale by percentage.",
    longDescription: "Resize photos with precise dimensions, useful presets, and aspect-ratio control.",
    category: "Resize",
    status: "active",
    icon: Maximize2,
    accent: "violet",
    related: ["compress-image", "passport-photo-maker", "resize-image-to-kb"],
  },
  {
    name: "Crop & Rotate Image",
    slug: "crop-image",
    description: "Crop, rotate, and flip an image with precise aspect ratios.",
    longDescription: "Crop and straighten photos locally with common aspect ratios, rotation, and flip controls.",
    category: "Edit",
    status: "active",
    icon: Crop,
    accent: "cyan",
    related: ["resize-image", "compress-image", "passport-photo-maker"],
  },
  {
    name: "Convert Image",
    slug: "convert-image",
    description: "Convert HEIC, AVIF, PNG, JPG, and WebP locally.",
    longDescription: "Change iPhone and web image formats locally with transparency handling and quality controls.",
    category: "Conversion",
    status: "active",
    icon: RefreshCw,
    accent: "sky",
    related: ["batch-converter", "compress-image", "resize-image"],
  },
  {
    name: "Image to PDF",
    slug: "image-to-pdf",
    description: "Combine one or more images into a clean PDF.",
    longDescription: "Arrange JPG, PNG, and WebP images into a downloadable PDF with page-size and margin controls.",
    category: "Documents",
    status: "active",
    icon: FileImage,
    accent: "amber",
    related: ["compress-image", "resize-image", "convert-image"],
  },
  {
    name: "Batch Converter",
    slug: "batch-converter",
    description: "Convert a queue of images and download one ZIP.",
    longDescription: "Process multiple images without uploading them, then download files individually or together.",
    category: "Batch tools",
    status: "active",
    icon: Images,
    accent: "amber",
    related: ["convert-image", "compress-image", "resize-image"],
  },
  {
    name: "Resize Image to KB",
    slug: "resize-image-to-kb",
    description: "Aim for 20 KB, 50 KB, 100 KB, or a custom size.",
    longDescription: "Use bounded quality and dimension optimization to approach a practical target file size.",
    category: "Optimization",
    status: "active",
    icon: Aperture,
    accent: "rose",
    related: ["compress-image", "resize-image", "convert-image"],
  },
  {
    name: "Signature Resizer",
    slug: "signature-resizer",
    description: "Prepare signatures for exam and application portals.",
    longDescription: "Resize and compress a signature to practical pixel and KB limits using source-backed application presets.",
    category: "Applications",
    status: "active",
    icon: PenLine,
    accent: "rose",
    related: ["resize-image-to-kb", "resize-image", "passport-photo-maker"],
  },
  {
    name: "Passport Photo Maker",
    slug: "passport-photo-maker",
    description: "Crop and position portraits for common photo sizes.",
    longDescription: "Prepare a portrait with configurable presets, zoom, positioning, and high-resolution export.",
    category: "Passport",
    status: "active",
    icon: ScanFace,
    accent: "indigo",
    related: ["resize-image", "compress-image", "resize-image-to-kb"],
  },
];

export const getTool = (slug: string) => tools.find((tool) => tool.slug === slug);
