import {
  Aperture,
  Crop,
  FileImage,
  ImageDown,
  Images,
  Maximize2,
  PenLine,
  RefreshCw,
  ScanFace,
  FileStack,
  Scissors,
  LayoutList,
  RotateCw,
  FlipHorizontal,
  Wand2,
  Type,
} from "lucide-react";
import type { ToolConfig } from "@/types/tool";

export const tools: ToolConfig[] = [
  // Core Engines (shown in shortcuts, filtered from grid)
  {
    name: "Compress Image",
    slug: "compress-image",
    description: "Shrink JPG, PNG, and WebP files without a watermark.",
    longDescription: "Reduce image file size in your browser while keeping the visual quality you choose.",
    category: "Optimization",
    status: "active",
    icon: ImageDown,
    accent: "mint",
    related: ["resize-image", "convert-image", "resize-image-to-kb"],
  },
  {
    name: "Resize Image",
    slug: "resize-image",
    description: "Set exact dimensions or scale by percentage.",
    longDescription: "Resize photos with precise dimensions, useful presets, and aspect-ratio control.",
    category: "Resize",
    status: "active",
    icon: Maximize2,
    accent: "violet",
    related: ["compress-image", "crop-image", "resize-image-to-kb"],
  },
  {
    name: "Crop & Rotate Image",
    slug: "crop-image",
    description: "Crop, rotate, and flip an image with precise aspect ratios.",
    longDescription: "Crop and straighten photos locally with common aspect ratios, rotation, and flip controls.",
    category: "Edit",
    status: "active",
    icon: Crop,
    accent: "cyan",
    related: ["resize-image", "compress-image", "blur-image"],
  },
  {
    name: "Convert Image",
    slug: "convert-image",
    description: "Convert HEIC, AVIF, PNG, JPG, and WebP locally.",
    longDescription: "Change iPhone and web image formats locally with transparency handling and quality controls.",
    category: "Conversion",
    status: "active",
    icon: RefreshCw,
    accent: "sky",
    related: ["batch-converter", "compress-image", "jpg-to-png"],
  },

  // Most Popular Tools (shown by default in grid)
  {
    name: "Resize Image to KB",
    slug: "resize-image-to-kb",
    description: "Aim for 20 KB, 50 KB, 100 KB, or a custom size.",
    longDescription: "Use bounded quality and dimension optimization to approach a practical target file size.",
    category: "Optimization",
    status: "active",
    icon: Aperture,
    accent: "rose",
    related: ["compress-image", "resize-image", "bulk-image-compressor"],
  },
  {
    name: "Batch Converter",
    slug: "batch-converter",
    description: "Convert a queue of images and download one ZIP.",
    longDescription: "Process multiple images without uploading them, then download files individually or together.",
    category: "Batch tools",
    status: "active",
    icon: Images,
    accent: "amber",
    related: ["convert-image", "jpg-to-png", "bulk-image-compressor"],
  },
  {
    name: "JPG to PNG",
    slug: "jpg-to-png",
    description: "Convert JPG images to PNG format with transparency.",
    longDescription: "Transform JPG images to PNG locally with lossless quality and optional transparency.",
    category: "Conversion",
    status: "active",
    icon: RefreshCw,
    accent: "indigo",
    related: ["png-to-jpg", "convert-image", "compress-image"],
  },
  {
    name: "PNG to JPG",
    slug: "png-to-jpg",
    description: "Convert PNG images to JPG format.",
    longDescription: "Transform PNG images to JPG locally with quality control and file-size reduction.",
    category: "Conversion",
    status: "active",
    icon: RefreshCw,
    accent: "amber",
    related: ["jpg-to-png", "convert-image", "compress-image"],
  },
  {
    name: "Add Text to Image",
    slug: "add-text-to-image",
    description: "Add text overlays to images.",
    longDescription: "Add customizable text overlays to images with font, size, color, and position controls.",
    category: "Edit",
    status: "active",
    icon: Type,
    accent: "sky",
    related: ["blur-image", "crop-image", "compress-image"],
  },
  {
    name: "Blur Image",
    slug: "blur-image",
    description: "Add blur effects to images or regions.",
    longDescription: "Apply blur effects to entire images or selected regions for privacy and artistic effects.",
    category: "Edit",
    status: "active",
    icon: Wand2,
    accent: "violet",
    related: ["add-text-to-image", "crop-image", "pixelate-image"],
  },
  {
    name: "Bulk Image Compressor",
    slug: "bulk-image-compressor",
    description: "Compress multiple images at once.",
    longDescription: "Process a queue of images and download compressed versions individually or as a ZIP.",
    category: "Batch tools",
    status: "active",
    icon: Images,
    accent: "mint",
    related: ["batch-converter", "bulk-image-resizer", "compress-image"],
  },
  {
    name: "Signature Resizer",
    slug: "signature-resizer",
    description: "Prepare signatures for exam and application portals.",
    longDescription: "Resize and compress a signature to practical pixel and KB limits using source-backed application presets.",
    category: "Applications",
    status: "active",
    icon: PenLine,
    accent: "rose",
    related: ["resize-image-to-kb", "resize-image", "passport-photo-resizer"],
  },

  // Extended Tools (shown in expand section)
  {
    name: "PNG to WebP",
    slug: "png-to-webp",
    description: "Convert PNG images to WebP format.",
    longDescription: "Transform PNG images to modern WebP format locally for superior compression.",
    category: "Conversion",
    status: "active",
    icon: RefreshCw,
    accent: "violet",
    related: ["webp-to-png", "convert-image", "jpg-to-webp"],
  },
  {
    name: "WebP to PNG",
    slug: "webp-to-png",
    description: "Convert WebP images to PNG format.",
    longDescription: "Transform WebP images to PNG locally with full transparency support.",
    category: "Conversion",
    status: "active",
    icon: RefreshCw,
    accent: "mint",
    related: ["png-to-webp", "convert-image", "webp-to-jpg"],
  },
  {
    name: "WebP to JPG",
    slug: "webp-to-jpg",
    description: "Convert WebP images to JPG format.",
    longDescription: "Transform WebP images to JPG locally with quality control for broad compatibility.",
    category: "Conversion",
    status: "active",
    icon: RefreshCw,
    accent: "cyan",
    related: ["webp-to-png", "png-to-jpg", "convert-image"],
  },
  {
    name: "JPG to WebP",
    slug: "jpg-to-webp",
    description: "Convert JPG images to WebP format.",
    longDescription: "Transform JPG images to modern WebP format locally for superior compression.",
    category: "Conversion",
    status: "active",
    icon: RefreshCw,
    accent: "indigo",
    related: ["jpg-to-png", "png-to-webp", "convert-image"],
  },
  {
    name: "Bulk Image Resizer",
    slug: "bulk-image-resizer",
    description: "Resize multiple images to the same dimensions.",
    longDescription: "Resize a batch of images to unified dimensions and download them all in one package.",
    category: "Batch tools",
    status: "active",
    icon: Images,
    accent: "rose",
    related: ["batch-converter", "bulk-image-compressor", "resize-image"],
  },
  {
    name: "Pixelate Image",
    slug: "pixelate-image",
    description: "Pixelate images or regions for privacy.",
    longDescription: "Apply pixelation effects to images or specific areas for anonymity and artistic use.",
    category: "Edit",
    status: "active",
    icon: Wand2,
    accent: "sky",
    related: ["blur-image", "add-text-to-image", "watermark-image"],
  },
  {
    name: "Watermark Image",
    slug: "watermark-image",
    description: "Add watermarks to images.",
    longDescription: "Protect your images by adding text or image watermarks with customizable opacity and position.",
    category: "Edit",
    status: "active",
    icon: Type,
    accent: "rose",
    related: ["add-text-to-image", "blur-image", "pixelate-image"],
  },
  {
    name: "ID Photo Resizer",
    slug: "id-photo-resizer",
    description: "Resize ID photos to specification.",
    longDescription: "Prepare ID photos to official specifications for driver's licenses and state IDs.",
    category: "Applications",
    status: "active",
    icon: ScanFace,
    accent: "cyan",
    related: ["visa-photo-resizer", "passport-photo-resizer", "resize-image"],
  },
  {
    name: "Visa Photo Resizer",
    slug: "visa-photo-resizer",
    description: "Resize and prepare visa photos.",
    longDescription: "Prepare visa photos to specification for most visa and international applications.",
    category: "Applications",
    status: "active",
    icon: ScanFace,
    accent: "amber",
    related: ["id-photo-resizer", "passport-photo-resizer", "resize-image"],
  },
  {
    name: "Passport Photo Resizer",
    slug: "passport-photo-resizer",
    description: "Resize and prepare passport photos.",
    longDescription: "Prepare passport photos to official specifications for all major countries.",
    category: "Applications",
    status: "active",
    icon: ScanFace,
    accent: "indigo",
    related: ["id-photo-resizer", "visa-photo-resizer", "resize-image"],
  },
  {
    name: "Passport Photo Maker",
    slug: "passport-photo-maker",
    description: "Crop and position portraits for common photo sizes.",
    longDescription: "Prepare a portrait with configurable presets, zoom, positioning, and high-resolution export.",
    category: "Passport",
    status: "active",
    icon: ScanFace,
    accent: "indigo",
    related: ["resize-image", "passport-photo-resizer", "id-photo-resizer"],
  },

  // PDF Tools
  {
    name: "JPG to PDF",
    slug: "jpg-to-pdf",
    description: "Turn JPG, PNG, or WebP images into one PDF.",
    longDescription: "Arrange images into a clean PDF with page-size and margin controls, entirely on your device.",
    category: "PDF tools",
    status: "active",
    icon: FileImage,
    accent: "amber",
    related: ["pdf-to-jpg", "merge-pdf", "image-to-pdf"],
  },
  {
    name: "PDF to JPG",
    slug: "pdf-to-jpg",
    description: "Turn PDF pages into clear JPG images.",
    longDescription: "Export PDF pages as JPG images locally, with an adjustable output quality.",
    category: "PDF tools",
    status: "active",
    icon: FileImage,
    accent: "sky",
    related: ["jpg-to-pdf", "merge-pdf", "image-to-pdf"],
  },
  {
    name: "Merge PDF",
    slug: "merge-pdf",
    description: "Combine PDFs in the order you choose.",
    longDescription: "Join PDF files directly in your browser. Your documents never leave your device.",
    category: "PDF tools",
    status: "active",
    icon: FileStack,
    accent: "violet",
    related: ["split-pdf", "organize-pdf", "jpg-to-pdf"],
  },
  {
    name: "Split PDF",
    slug: "split-pdf",
    description: "Extract selected pages into a new PDF.",
    longDescription: "Choose a page range and download it as a separate PDF without uploading your file.",
    category: "PDF tools",
    status: "active",
    icon: Scissors,
    accent: "rose",
    related: ["merge-pdf", "organize-pdf", "pdf-to-jpg"],
  },
  {
    name: "Organize PDF",
    slug: "organize-pdf",
    description: "Reorder or keep only the pages you need.",
    longDescription: "Set a page order or remove pages from a PDF locally and download the revised document.",
    category: "PDF tools",
    status: "active",
    icon: LayoutList,
    accent: "mint",
    related: ["merge-pdf", "split-pdf", "pdf-to-jpg"],
  },
  {
    name: "Image to PDF",
    slug: "image-to-pdf",
    description: "Combine one or more images into a clean PDF.",
    longDescription: "Arrange JPG, PNG, and WebP images into a downloadable PDF with page-size and margin controls.",
    category: "Documents",
    status: "active",
    icon: FileImage,
    accent: "amber",
    related: ["jpg-to-pdf", "merge-pdf", "compress-image"],
  },
];

export const getTool = (slug: string) => tools.find((tool) => tool.slug === slug);
